server:
  context: /users
spring:
  jmx:
    default-domain: users-domain
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo_users;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
#        dialect: H2Dialect
        format_sql: true

#LOGGING CONFIGURATION
logging:
  level:
    org:
      hibernate:
        sql: info